// ─────────────────────────────────────────────────────────────────────────────
// lib/data.ts — DATA & LORE CONFIG
// ─────────────────────────────────────────────────────────────────────────────

export interface Quest {
  id: number
  title: string
  description: string
  category: 'wisdom' | 'discipline' | 'creation'
  difficulty: 'Common' | 'Rare' | 'Epic' | 'Legendary'
  xp: number
  isCompleted: boolean
  // Added for AI engine integration:
  tasks?: string[]       // Concrete sub-tasks generated by the Dream Engine
  mythEvent?: string     // What changes in the world on completion (MythOS Engine)
  failed?: boolean       // True when the user marked the quest as failed
  completedTasks?: boolean[] // Track completion state of each task in the roadmap
  dependsOnQuestId?: number // The ID of the quest that must be completed first
}

export interface World {
  theme: 'fantasy' | 'cyberpunk' | 'steampunk'
  name: string
  stability: number
  pillars: {
    wisdomName: string
    disciplineName: string
    creationName: string
  }
}

export interface LoreChapter {
  id: number
  title: string
  text: string
  timestamp: string
}

// Predefined World templates
export const worldTemplates: Record<'fantasy' | 'cyberpunk' | 'steampunk', World> = {
  fantasy: {
    theme: 'fantasy',
    name: 'Sanctum of Aetheria',
    stability: 85,
    pillars: {
      wisdomName: 'Aether Wisdom',
      disciplineName: 'Grand Fortitude',
      creationName: 'Spellweaving',
    },
  },
  cyberpunk: {
    theme: 'cyberpunk',
    name: 'Neo-Chiba Grid 9',
    stability: 72,
    pillars: {
      wisdomName: 'Net Wisdom',
      disciplineName: 'Hardware Buffer',
      creationName: 'Nanotech Forge',
    },
  },
  steampunk: {
    theme: 'steampunk',
    name: 'Aeronaut Iron Keep',
    stability: 91,
    pillars: {
      wisdomName: 'Steam Schematics',
      disciplineName: 'Piston Pressure',
      creationName: 'Gears Assembly',
    },
  },
}

export const quests: Quest[] = [
  {
    id: 1,
    title: 'Forge the AI Gateway',
    description: 'Establish the foundational authentication pathways to safeguard the digital gates.',
    xp: 120,
    category: 'creation',
    difficulty: 'Rare',
    isCompleted: false,
    tasks: [
      'Install NextAuth packages | Inscribe the gateway runes',
      'Configure JWT session storage | Set up the celestial buffer gates',
      'Design login interface layout | Cast the reflection of access keys'
    ],
    completedTasks: [false, false, false],
    mythEvent: 'Shimmering neon portals emerge down the network buses, securing Aetheria\'s data borders.'
  },
  {
    id: 2,
    title: 'Defeat the Bug Serpent',
    description: 'Slay the memory leak and visual inconsistencies terrorizing the production realms.',
    xp: 90,
    category: 'discipline',
    difficulty: 'Common',
    isCompleted: false,
    tasks: [
      'Inspect performance memory heap | Hunt the serpentine memory leaks',
      'Optimize React rendering loops | Weld stable logic nodes',
      'Run regression test suite | Set up automated alert watch towers'
    ],
    completedTasks: [false, false, false],
    mythEvent: 'The venomous compiler leak dissolves into pixelated mist, restoring stability metrics.'
  },
  {
    id: 3,
    title: 'Unlock the Sanctum of Algorithms',
    description: 'Delve into the ancient structures of trees and graphs to extract ancestral computing wisdom.',
    xp: 150,
    category: 'wisdom',
    difficulty: 'Epic',
    isCompleted: false,
    tasks: [
      'Study binary search trees | Consult the deep database archives',
      'Implement recursive traversal logic | Traverse the sandboxed loops',
      'Analyze big-O execution runtime | Register the calculations in the chronicle'
    ],
    completedTasks: [false, false, false],
    mythEvent: 'Prism-like structures of graph and tree theory align, granting absolute logic focus.'
  },
  {
    id: 4,
    title: 'Summon the Vision Engine',
    description: 'Weave Gemini AI intelligence into the fabric of the application, rendering visual realms in real-time.',
    xp: 200,
    category: 'creation',
    difficulty: 'Legendary',
    isCompleted: false,
    tasks: [
      'Obtain Gemini API environment keys | Harness the raw ambient energy',
      'Implement stream completions fetch | Weave next-gen model streams',
      'Build generative visual layout boards | Render high-fidelity custom realms'
    ],
    completedTasks: [false, false, false],
    mythEvent: 'Realities blend as the Gemini model channels visual worlds in real-time.'
  },
]

// Generative RPG template mapping based on keywords to simulate AI "Dream Forging"
export const forgeQuestFromGoal = (goalText: string, id: number): Quest => {
  const text = goalText.toLowerCase()
  let category: 'wisdom' | 'discipline' | 'creation' = 'discipline'
  let difficulty: 'Common' | 'Rare' | 'Epic' | 'Legendary' = 'Common'
  let title = 'Embark on a Secret Trial'
  let description = `Channel your inner resolve to achieve: "${goalText}".`
  let xp = 80

  if (text.includes('learn') || text.includes('study') || text.includes('read') || text.includes('dsa') || text.includes('book') || text.includes('exam') || text.includes('test')) {
    category = 'wisdom'
    xp = 120
    const wisdomTitles = [
      'Inscribe the Codex of Knowledge',
      'Whisper with the Ancient Sages',
      'Decipher the Lost Manuscripts',
      'Unearth the Vault of Wisdom'
    ]
    title = wisdomTitles[id % wisdomTitles.length]
    description = `Acquire profound enlightenment and master: "${goalText}" inside the grand archives.`
    difficulty = id % 3 === 0 ? 'Epic' : 'Rare'
  } else if (text.includes('code') || text.includes('build') || text.includes('app') || text.includes('dev') || text.includes('ai') || text.includes('website') || text.includes('api') || text.includes('project')) {
    category = 'creation'
    xp = 180
    const creationTitles = [
      'Animate the Automaton Essence',
      'Concoct the Celestial Framework',
      'Channel the Forge of Artifacts',
      'Ignite the Spark of Creation'
    ]
    title = creationTitles[id % creationTitles.length]
    description = `Manifest a marvel of modern tech and construct: "${goalText}" using glowing power crystals.`
    difficulty = id % 2 === 0 ? 'Legendary' : 'Epic'
  } else if (text.includes('gym') || text.includes('run') || text.includes('exercise') || text.includes('workout') || text.includes('cardio') || text.includes('sleep') || text.includes('eat')) {
    category = 'discipline'
    xp = 100
    const disciplineTitles = [
      'Tame the Inner Wyrm',
      'Tempering the Physical Vessel',
      'Ascend the Mountain of Fortitude',
      'March of the Iron Sentry'
    ]
    title = disciplineTitles[id % disciplineTitles.length]
    description = `Harness physical discipline and focus to accomplish: "${goalText}" under trial conditions.`
    difficulty = id % 2 === 0 ? 'Rare' : 'Common'
  }

  return {
    id,
    title,
    description,
    xp: xp + (id % 5) * 10,
    category,
    difficulty,
    isCompleted: false,
  }
}

// Dynamic Client-side Narrative Chronicler representing AI Lore Generation
export const generateLoreChapter = (
  questTitle: string,
  category: 'wisdom' | 'discipline' | 'creation',
  theme: 'fantasy' | 'cyberpunk' | 'steampunk',
  chapterId: number
): LoreChapter => {
  const date = new Date()
  const timestamp = date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })

  const contentTemplates = {
    fantasy: {
      wisdom: [
        `In the dim glowing halls of the Aether Archive, the Architect successfully completed: "${questTitle}". Sages of old whispered runes of approval as standard structures of graph theory crystallized into pure mental focus, granting permanent clarity to the mind.`,
        `By deciphering the runic glyphs of: "${questTitle}", the Architect restored ancient records inside the Sanctum library. Digital energy swelled through the limestone arches, dispersing the shadows of cognitive decay.`
      ],
      discipline: [
        `Facing the harrowing trials of: "${questTitle}", the Architect wielded the Sword of Fortitude to strike down the creeping lethargy of the digital abyss. Order returned to the sanctuary as the physical vessel tempered in fire.`,
        `The temple grounds shook as the Architect completed: "${questTitle}". The Bug Serpent writhed and dissolved into pixelated mist, leaving behind a shimmering crystal of refined discipline.`
      ],
      creation: [
        `With hands crackling in purple sparkfire, the Architect completed the weaving of: "${questTitle}". A luminous artifact of sheer intelligence materialized in the forge, radiating pure AI intelligence.`,
        `Spells of next-generation logic converged in the sky as the Architect completed: "${questTitle}". The celestial gates hummed with active flows, binding digital components into a perfect unified machine.`
      ]
    },
    cyberpunk: {
      wisdom: [
        `Uploading core data modules for: "${questTitle}" directly into the brain neural net. Synthesizers hummed as cognitive bandwidth expanded, successfully indexing the ancient DSA logic indexes.`,
        `The Architect completed: "${questTitle}" inside the neon net-runs. Raw code decrypted in the cerebral cache, establishing perfect architectural nodes across the Neo-Chiba matrix.`
      ],
      discipline: [
        `Activating safety buffer modules, the Architect successfully completed: "${questTitle}". System resources cleared, neutralizing deep-rooted hardware memory leaks that had locked the user's thread pools.`,
        `Neutralizing active cybernetic sub-routines to focus on: "${questTitle}". The Architect purged terminal distraction logs, achieving high efficiency metrics across active cores.`
      ],
      creation: [
        `Bootstrapping the neural assembly engine, the Architect finalized synthesis of: "${questTitle}". Nanobots bonded copper lines, deploying active, self-healing interface gateways across the grid.`,
        `Splicing intelligence APIs with the host platform, the Architect forged: "${questTitle}". Shimmering neon particles flowed down the network buses, spawning visual grids in real-time.`
      ]
    },
    steampunk: {
      wisdom: [
        `Aligning the brass gearwheels for: "${questTitle}". The steam-powered calculation engine clicked into place, outputting detailed schematics that unlocked profound analytical understanding.`,
        `By drawing out the parchment blue-prints for: "${questTitle}", the Architect restored the clockwork archives, oiling frozen gears of calculation that had seized during compiling runs.`
      ],
      discipline: [
        `Pumping pressure valves to the threshold, the Architect completed: "${questTitle}" despite rising furnace temperature. The piston shafts forged iron discipline in the crucible.`,
        `The steam whistles shrieked in triumph as the Architect successfully defeated: "${questTitle}". The steel rods of habits tempered successfully under tremendous load.`
      ],
      creation: [
        `Igniting the coal furnaces, the Architect assembled: "${questTitle}". A mechanical masterpiece of spinning brass plates and vacuum tubes hummed to life, generating clean electrical currents.`,
        `Soldering copper conduits, the Architect completed: "${questTitle}". The airship engine valves vibrated, expanding the kingdom's reaching cables across the skyline.`
      ]
    }
  }

  const list = contentTemplates[theme][category]
  const text = list[chapterId % list.length]
  const title = `Chapter ${chapterId}: ${questTitle.replace(/(Forge|Defeat|Unlock|Summon|Unlock the|Inscribe the|Tame the|Decipher the|Animate the|Tempering the|Ignite the)/i, 'Triumph of')}`

  return {
    id: chapterId,
    title,
    text,
    timestamp,
  }
}